version: '3.9'

services:
  api:
    container_name: ot292-app
    hostname: api-ong
    build: 
        context: .
        target: Production
    ports:
      - '3000:3000'
    restart: always
    environment:
      - ${DB_NAME}
      - ${DB_USER}
      - ${DB_PASSWORD}
      - ${DB_PORT}
      - ${DB_HOST}
      - ${JWT_SECRET}
    command: npm run start
    links:
      - mysql
  mysql:
    container_name: mysql_db
    hostname: mysupersqldatabase
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ong
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql-data:

